### ISSUE TITLE
firefox: failing https certificates

### ISSUE THREAD

**Issue by star-buck** [netrunner-odroid/issues#1]
![screenshot_19800101_011307](https://cloud.githubusercontent.com/assets/840070/15455128/0f01ff6a-204b-11e6-9d6a-3bc7c2066811.png)

**Comment by shadeslayer** [comment]
@star-buck could you give me the output of

``` sh
date -R
apt-cache policy ca-certificates
```

**Comment by shadeslayer** [comment]
Should be fixed now, can you check and close the issue?

**Comment by star-buck** [comment]
fixed
