### ISSUE TITLE
don't require screen / keyboard / mice after first boot

### ISSUE THREAD

**Issue by adrelanos** [netrunner-odroid/issues#12]
Just flashed... http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stretch/armhf/netrunner-core/netrunner-core-20161213.1334-armhf.img.gz

After doing that, there is no way to just plug in the sd card, a lan cable [or wifi stick] plus power and start using (`ssh`ing) the odroid.

This is because after flashing, the system is booting with the `live` user. There is no sshd server running. One has to click and run the netrunner odroid first installation setup.

The netrunner odroid first installation setup does some useful stuff such as resizing the image (so the full sd card space is used) as well as choosing the keyboard layout.

There is no way to complete this without attaching more devices. One needs to plug a hdmi monitor, a keyboard (and mice).

Depending on the target audience of netrunner-odroid you may or may not consider this as a feature request.

feature request:
It would be cool if ssh and vnc was already running with a default username and default password. Then one could fully configure the odroid over the network.

**Comment by star-buck** [comment]
That should already be the case:
First time boot, enter live-pc:5900 in any browser on the same network.

Login/pwd: live/live

Then after installation and reboot, again vnc is started, this time access
with the hostname you have chosen during installation again over port 5900
and username password you have chosen.

This should work over any browser or of course vnc client.

**Comment by adrelanos** [comment]
Interesting! I am going to test this now.

**Comment by star-buck** [comment]
You can also double-click on the secure vnc link on the desktop to start
another vnc instance listening on port 6900, but its not a switch between
secure and insecure yet, as one has to manually stop the 5900 connection or
both fun at the same time. For the 6900 one you need a client though like
tigervnc.

**Comment by adrelanos** [comment]
Then this might be mostly a documentation issue then.

Do you already have a homepage / some documentation on netrunner-odroid?

-----

I think out of the box only browser vnc (noVNC) will work.

* This is because only noVNC listens on all interfaces on port 5900.
* x11vnc listens on localhost only.
* noVNC is not compatible with regular VNC viewers such as xvncviewer. (Not sure, but just now [asked](https://github.com/novnc/noVNC/issues/741).)
* ssh won't work because apparently netrunner-odroid is apparently shipping by default a hardened `/etc/ssh/sshd_config` that disables password based login?

Still, having noVNC is great!

-----

```
live@live-pc:~$ sudo netstat -tulpen                                                                                                                          
Active Internet connections (only servers)                                                                                                                    
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name                                        
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      1000       12045      1606/python                                             
tcp        0      0 127.0.0.1:43183         0.0.0.0:*               LISTEN      1000       13699      1608/x11vnc                                             
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          34339      15637/sshd                                                                    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      0          5774       917/cupsd                                                                     
tcp6       0      0 :::5900                 :::*                    LISTEN      1000       13700      1608/x11vnc                                                                   
tcp6       0      0 :::22                   :::*                    LISTEN      0          31717      15637/sshd          
tcp6       0      0 ::1:631                 :::*                    LISTEN      0          5773       917/cupsd           
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          7138       992/dhclient        
udp        0      0 0.0.0.0:631             0.0.0.0:*                           0          7099       972/cups-browsed    
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           112        5748       918/avahi-daemon: r 
udp        0      0 0.0.0.0:53627           0.0.0.0:*                           112        5750       918/avahi-daemon: r 
udp6       0      0 :::51347                :::*                                112        5751       918/avahi-daemon: r 
udp6       0      0 :::5353                 :::*                                112        5749       918/avahi-daemon: r 
live@live-pc:~$ 
```

-----

That domain name `live-pc` isn't working for me.

```
nslookup live-pc
```

```
Server:         10.137.2.1
Address:        10.137.2.1#53

** server can't find live-pc: NXDOMAIN
```

I have to figure out the IP somehow (looking in my router web interface for connected IPs) and use that.

I am not sure how resolving `live-pc` could work. I mean, usually (also in my case) DNS is auto configured to my router, and my router uses my ISPs DNS server. As far I know, home routers have no feature for any connected devices such as the odroid to add/remove any DNS entries in the home router.

Or does netrunner-odroid configure avahi? I have the avahi-discover package installed. Yet, `nslookup live-pc.local` also fails for me. Anything else required for making the local DNS work?

-----

Perhaps could be added to documentation. Some issue that I did run into. :-)

> Hint: You need to do this from a VM that does not get tunneled through a VPN. If you don't know what a VPN is or if you are using one, then you are probably not using one and can forget about this.

**Comment by adrelanos** [comment]
I finally wrapped by head around avahi and `.local` addresses.

> First time boot, enter live-pc:5900 in any browser on the same network.

That will almost certainly not work. What could work is with `.local` suffix, i.e. `live-pc.local:5900`.

Without `.local` (avahi), I see no way how this could work.

And in Chrome one has to enter `http://live-pc.local:5900` - otherwise Chrome redirects to Google. In Firefox `live-pc.local:5900` without `http://` prefix worked for me also.

Getting `.local` / avahi to work is not that simple. At least not for me. :-)

* Also the client computer has to have avahi-daemon installed. (`sudo apt-get avahi-daemon`)
* Also firewalls can interfere. With a common "block non-whitelisted ports by default" firewall on the client computer it will not work. (https://wiki.archlinux.org/index.php/avahi#Firewall)

-----

I don't know yet if it is possible to make `live-pc.local` work. However, perhaps not required. Chrome / Firefox / xvncviewer all speak avahi. Useful for testing: `avahi-resolve-host-name live-pc.local`.

**Comment by shadeslayer** [comment]
live-pc.local:5900 works perfectly fine on my network here. So it's entirely possible any issues related to .local addresses could be with your network setup.

**Comment by adrelanos** [comment]
It certainly has to do with ones network and software configuration. I discussed these addresses a while ago with @star-buck and just wanted to point that out, I am sure many users will run into this, good to be aware of this.

**Comment by star-buck** [comment]
main ticket topic is done, lets watch this again with later images and open another ticket if necessary
