### ISSUE TITLE
iptables broken - modprobe: ERROR: could not insert 'ip_tables': Unknown symbol in module, or unknown parameter (see dmesg)

### ISSUE THREAD

**Issue by adrelanos** [netrunner-odroid/issues#13]
Currently using http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stretch/armhf/netrunner-core/netrunner-core-20161213.1334-armhf.img.gz

```
sudo iptables --list
```

```
modprobe: ERROR: could not insert 'ip_tables': Unknown symbol in module, or unknown parameter (see dmesg)
iptables v1.6.0: can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```

`dmesg` includes:
```
[ 1643.543774] ip_tables: Unknown symbol _GLOBAL_OFFSET_TABLE_ (err 0)
```

**Comment by shadeslayer** [comment]
This is a PIE issue with the kernel build and has since been fixed.

**Comment by shadeslayer** [comment]
Correction, apparently the build failed and I did not notice. I'm looking into this.

**Comment by shadeslayer** [comment]
Issue has been fixed. Please add this repo :

```
deb http://dci.ds9.pub:8080/odroid testing main
```

and upgrade to check.

**Comment by adrelanos** [comment]
Just now upgraded. Maybe there were some issues that I just now reported here #17. Will reboot now and tell you if the issue was solved.

**Comment by adrelanos** [comment]
The upgrade fixes this issue for me.

**Comment by shadeslayer** [comment]
Closing
