### ISSUE TITLE
mali-packages: versioning wrong, update manager wants to "update" to OLDER ones

### ISSUE THREAD

**Issue by star-buck** [netrunner-odroid/issues#4]
![screenshot_19800101_010849](https://cloud.githubusercontent.com/assets/840070/15455137/58197d90-204b-11e6-8f3d-d6740e39a918.png)

**Comment by star-buck** [comment]
affects both mali-x11 and xserver-xorg-video-mali

**Comment by shadeslayer** [comment]
Should be fixed now, could you please close the issue?

**Comment by star-buck** [comment]
seems fixed as of 20160527
