### ISSUE TITLE
Question: why is flashed IMG on sd microcard default EXT2?

### ISSUE THREAD

**Issue by star-buck** [netrunner-odroid/issues#5]
any reason or could/should we use ext4?

**Comment by shadeslayer** [comment]
Hi Clemens
The default partition should already be ext4.

In order to debug this, could you provide me the output of

``` bash
sudo blkid /dev/mmcblk0p1
```

I've just checked netrunner-debian_20160520.1701.img locally and gparted says the partition is ext4, as does blkid :

```
/dev/mmcblk0p1: LABEL="ROOT" UUID="1b6df582-f8d9-486b-ac40-8985a8369e73" TYPE="ext4" PARTUUID="cac4de21-01"
```

**Comment by star-buck** [comment]
that says ext4, closing this then
