### ISSUE TITLE
idea: add icon on desktop to start new x11vnc session if clicked (for realvnc etc. under "hostname:6900")

### ISSUE THREAD

**Issue by star-buck** [netrunner-odroid/issues#6]

**Comment by shadeslayer** [comment]
The end use case being that multiple users can login and launch different sessions?

**Comment by star-buck** [comment]
for a start, we can end any other session like novnc and establish a new one.
novnc is great for quick access, but for longer vnc sessions, realvnc is beter due to copy and paste flexible screen size etc.

**Comment by shadeslayer** [comment]
This is done?
