### ISSUE TITLE
image download

### ISSUE THREAD

**Issue by adrelanos** [netrunner-odroid/issues#7]
Do you have any downloadable images and/or website for netrunner-odroid?

**Comment by star-buck** [comment]
yes, still Beta version though availble here:
http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stable/armhf/netrunner-core/netrunner-core-20160926.1357-dev-armhf.img.gz

**Comment by adrelanos** [comment]
Any newer images available?

**Comment by adrelanos** [comment]
http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stretch/armhf/netrunner-core/netrunner-core-20161213.1334-armhf.img.gz

**Comment by adrelanos** [comment]
Easy command to download all netrunner-odroid repos.

    ORG=netrunner-odroid; curl "https://api.github.com/orgs/$ORG/repos?per_page=1000" | grep -o 'git@[^"]*' | xargs -L1 git clone

(Courtesy to http://stackoverflow.com/a/32803025/2605155.)

**Comment by shadeslayer** [comment]
@adrelanos FYI the image linked is not release ready yet.

**Comment by adrelanos** [comment]
Alright. Count me in as an early tester. The odroid / netrunner-odroid became really neat.
