### ISSUE TITLE
Kernel panic - not syncing: hung_task: blocked tasks

### ISSUE THREAD

**Issue by adrelanos** [netrunner-odroid/issues#8]
Currently testing http://s3-eu-central-1.amazonaws.com/ds9-eu/dci/images/stretch/armhf/netrunner-core/netrunner-core-20161213.1334-armhf.img.gz

Got this during `sudo reboot`.

```
kernel:[ 3123.957975@1] Kernel panic - not syncing: hung_task: blocked tasks
```

**Comment by shadeslayer** [comment]
Does this get in the way of rebooting the device? I can reboot just fine here.

**Comment by adrelanos** [comment]
Rohan Garg:
> Does this get in the way of rebooting the device?

Yes. I had to plug out the power cable.

**Comment by shadeslayer** [comment]
Could be because of the incorrectly built kernel, please try and upgrade as requested in the other thread and let me know if the problem still persists.

**Comment by adrelanos** [comment]
No more kernel panic.

journal did not work out of the box.

```
sudo journalctl -b1
Specifying boot ID has no effect, no persistent journal was found
```
Needed to apply this solution:
http://askubuntu.com/a/858126/389275

```
mkdir -p /var/log/journal
systemd-tmpfiles --create --prefix /var/log/journal
systemctl restart systemd-journald
```
(Otherwise I couldn't have checked the shutdown log.)

Is journal intentionally disabled?

**Comment by shadeslayer** [comment]
Nope, should be enabled by default, but entirely possible that a busted kernel caused the journal to not be init'd?

**Comment by adrelanos** [comment]
No idea. Quite possibly a follow up issue indeed. Let's look out for
this when a new image is released.

**Comment by shadeslayer** [comment]
The journal issue is a bug in Debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717388

**Comment by shadeslayer** [comment]
I'm closing the bug since the reboot issue is fixed with the new kernel.
